project:
  type: website
  output-dir: docs

website:
  title: "Ben Quilligan"
  favicon: favicon/favicon-96x96.png
  navbar:
    title: false
    logo: /Users/benquilligan/ChatGPT Image Mar 3, 2026, 02_37_51 PM.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



