project:
  type: website
  output-dir: docs

website:
  title: "Ben Quilligan"
  favicon: favicon/favicon-96x96.png
  navbar:
    title: false
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: styles.scss
    mainfont: Montserrat
    toc: true
    page-layout: full
      
      
    



